import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import Footer from '../components/Footer'

export default function AIDisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 mb-8 transition-colors">
          <ArrowLeft className="h-5 w-5" /> Back to Home
        </Link>

        <div className="bg-white border border-slate-200 rounded-2xl p-8 md:p-12 shadow-sm">
          <h1 className="text-4xl font-bold mb-8 text-slate-900" style={{ fontFamily: 'Poppins, sans-serif' }}>AI & Decision Support Disclaimer</h1>

          <div className="prose prose-slate max-w-none space-y-8 text-slate-600" style={{ fontFamily: 'Inter, sans-serif' }}>
            <p className="text-sm text-slate-500">Last Updated: May 14, 2026</p>

            <div className="bg-amber-50 border border-amber-200 rounded-lg p-6">
              <p className="text-amber-800 font-semibold text-lg mb-2">Important Notice Regarding AI-Generated Outputs</p>
              <p className="text-amber-700">This disclaimer applies to all artificial intelligence features, insights, analyses, and outputs provided by the Procuvex&trade; platform. Please read this disclaimer carefully before using our services.</p>
            </div>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Nature of Service</h2>
              <p>Procuvex provides AI-powered document analysis, compliance tracking, risk assessment, and procurement intelligence through its platform. The platform uses artificial intelligence and machine learning technologies to analyze uploaded documents and generate structured outputs.</p>
              <p className="mt-4 font-semibold text-slate-800">Procuvex does NOT make bid/no-bid decisions on behalf of users. All outputs are advisory and informational only.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>User Responsibility</h2>
              <p className="font-semibold text-slate-800">You remain solely responsible for all decisions and actions taken based on information provided by the Procuvex platform.</p>
              <p className="mt-4">The analyses, compliance matrices, risk assessments, recommendations, and other outputs generated by Procuvex are intended to support and inform your decision-making processes. They are not intended to replace human judgment, professional expertise, or independent verification.</p>
              <p className="mt-4">Before acting on any information provided by Procuvex, you should:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Verify the accuracy of AI-extracted requirements against source documents</li>
                <li>Have qualified procurement professionals review compliance matrices</li>
                <li>Independently validate pricing and risk assessments</li>
                <li>Consult with legal counsel regarding regulatory compliance obligations</li>
                <li>Use your professional judgment and organizational knowledge to supplement AI outputs</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>AI Limitations</h2>
              <p>AI-generated outputs may:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Contain errors, omissions, or misinterpretations of source documents</li>
                <li>Miss requirements that are implied but not explicitly stated</li>
                <li>Incorrectly categorize or prioritize certain items</li>
                <li>Not account for regulatory changes or interpretations that occurred after the AI model's training data</li>
                <li>Vary in quality depending on the clarity and completeness of uploaded documents</li>
              </ul>
              <p className="mt-4">The quality of AI analysis depends on the quality and completeness of the documents provided. Incomplete, illegible, or poorly structured documents may produce less accurate results.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Compliance & Regulatory Matters</h2>
              <p>Procuvex compliance matrices and requirement extractions are AI-generated starting points. They are NOT certified compliance assessments. Your organization is responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Final compliance determinations for all bid submissions</li>
                <li>Ensuring proposals meet all applicable regulations (FAR, DFARS, state/local procurement codes)</li>
                <li>Verifying that subcontractor certifications and qualifications are current and valid</li>
                <li>Meeting all submission requirements, deadlines, and format specifications</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>No Guarantee of Outcomes</h2>
              <p className="font-semibold text-slate-800">Use of Procuvex does not guarantee any particular bid outcome, contract award, or business result.</p>
              <p className="mt-4">Bid readiness indicators, smart recommendations, and analytics are based on factual project data and AI analysis. They reflect the current state of preparation, not a prediction of success.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Data Processing</h2>
              <p>Document content is processed by AI systems to generate analysis outputs. By using Procuvex's AI features, you acknowledge and consent to this processing. We do not train AI models on your documents, and your data is not shared with other organizations. See our <Link to="/privacy" className="text-blue-600 hover:text-blue-700">Privacy Policy</Link> for full details.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Contact</h2>
              <p>If you have questions about this disclaimer or Procuvex's AI capabilities, please contact us at <a href="mailto:support@procuvex.com" className="text-blue-600 hover:text-blue-700">support@procuvex.com</a>.</p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
