import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import Footer from '../components/Footer'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 mb-8 transition-colors">
          <ArrowLeft className="h-5 w-5" /> Back to Home
        </Link>

        <div className="bg-white border border-slate-200 rounded-2xl p-8 md:p-12 shadow-sm">
          <h1 className="text-4xl font-bold mb-8 text-slate-900" style={{ fontFamily: 'Poppins, sans-serif' }}>Terms of Service</h1>

          <div className="prose prose-slate max-w-none space-y-8 text-slate-600" style={{ fontFamily: 'Inter, sans-serif' }}>
            <p className="text-sm text-slate-500">Last Updated: May 14, 2026</p>

            <p className="text-lg">
              These Terms of Service ("Terms") govern your access to and use of the Procuvex&trade; platform and services
              provided by Core314&trade; Technologies LLC ("Core314," "we," "us," or "our"). By accessing or using our
              services, you agree to be bound by these Terms.
            </p>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>1. Acceptance of Terms</h2>
              <p>By accessing, browsing, or using the Procuvex platform, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you are using the services on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.</p>
              <p className="mt-4">If you do not agree to these Terms, you must not access or use our services.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>2. Description of Service</h2>
              <p>Procuvex is an AI-powered procurement operating system that helps organizations manage bids, analyze documents, track compliance, coordinate subcontractors, and gain intelligence across procurement projects. The platform uses artificial intelligence to analyze uploaded documents and generate outputs including requirement extractions, compliance matrices, risk assessments, and recommendations.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>3. Account Responsibilities</h2>
              <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.</p>
              <p className="mt-4">Organization owners are responsible for managing team member access, roles, and permissions within their organization.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>4. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Upload malicious files, malware, or content that violates applicable laws</li>
                <li>Attempt to access other organizations' data or circumvent security controls</li>
                <li>Use the platform to store or transmit classified or export-controlled information unless explicitly authorized</li>
                <li>Reverse engineer, decompile, or attempt to extract source code from the platform</li>
                <li>Use automated tools to scrape or extract data beyond the provided API</li>
                <li>Resell or redistribute the service without authorization</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>5. AI-Generated Content</h2>
              <p className="font-semibold text-slate-800">All AI-generated outputs are advisory and informational only.</p>
              <p className="mt-4">Procuvex uses artificial intelligence to analyze documents and generate outputs such as requirement extractions, compliance matrices, pricing risk assessments, executive summaries, and recommendations. These outputs:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Are generated by AI and may contain errors or omissions</li>
                <li>Do not constitute legal, financial, or professional procurement advice</li>
                <li>Should be reviewed by qualified personnel before use in bid submissions</li>
                <li>Do not guarantee any particular bid outcome</li>
              </ul>
              <p className="mt-4">You remain solely responsible for all bid decisions, proposal content, and regulatory compliance. See our <Link to="/ai-disclaimer" className="text-blue-600 hover:text-blue-700">AI & Decision Support Disclaimer</Link> for full details.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>6. Intellectual Property</h2>
              <p>You retain all rights to documents you upload and content you create on the platform. We claim no ownership of your data.</p>
              <p className="mt-4">The Procuvex platform, including its design, code, AI models, and documentation, is the intellectual property of Core314 Technologies LLC and is protected by applicable intellectual property laws.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>7. Limitation of Liability</h2>
              <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, CORE314 SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL, ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICE.</p>
              <p className="mt-4">IN NO EVENT SHALL CORE314'S TOTAL LIABILITY EXCEED THE AMOUNT PAID BY YOU FOR THE SERVICE DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>8. Indemnification</h2>
              <p>You agree to indemnify and hold harmless Core314, its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the service, your violation of these Terms, or your violation of any third-party rights.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>9. Termination</h2>
              <p>Either party may terminate these Terms at any time. Upon termination, your right to access the service ceases immediately. We may retain your data for a reasonable period to comply with legal obligations.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>10. Governing Law</h2>
              <p>These Terms shall be governed by and construed in accordance with the laws of the State of Maryland, United States, without regard to conflict of law principles.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>11. Contact</h2>
              <p>For questions about these Terms, contact us at <a href="mailto:support@govmatchai.com" className="text-blue-600 hover:text-blue-700">support@govmatchai.com</a>.</p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
