-- =====================================================================================
-- Phase 7 Seed Data for E2E Testing
-- =====================================================================================

-- Insert sample decision events for test users
INSERT INTO decision_events (
  user_id,
  decision_type,
  trigger_source,
  context_data,
  reasoning_model,
  reasoning_response,
  factors_analyzed,
  total_confidence_score,
  recommended_action,
  action_details,
  expected_impact,
  risk_level,
  status,
  priority,
  tags
) VALUES
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    'optimization',
    'scheduled',
    '{"metric": "response_time", "current_value": 250, "threshold": 200}',
    'gpt-4o',
    'Based on current response time metrics, I recommend scaling up resources to maintain optimal performance.',
    '[{"factor_name": "response_time", "weight": 0.8, "value": 250, "score": 0.75}, {"factor_name": "error_rate", "weight": 0.2, "value": 0.5, "score": 0.95}]',
    0.8250,
    'approve',
    '{"action": "scale_up", "target_replicas": 3}',
    'Improved response time by 30%',
    'low',
    'pending',
    5,
    ARRAY['performance', 'optimization', 'automated']
  ),
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    'alert',
    'threshold',
    '{"metric": "error_rate", "current_value": 5.2, "threshold": 5.0}',
    'gpt-4o',
    'Error rate has exceeded threshold. Recommend investigating recent deployments.',
    '[{"factor_name": "error_rate", "weight": 0.9, "value": 5.2, "score": 0.60}, {"factor_name": "deployment_time", "weight": 0.1, "value": 1, "score": 0.80}]',
    0.6200,
    'escalate',
    '{"action": "investigate", "priority": "high"}',
    'Prevent service degradation',
    'medium',
    'pending',
    8,
    ARRAY['reliability', 'alert', 'threshold_breach']
  )
ON CONFLICT DO NOTHING;

-- Insert sample system health events for test users
INSERT INTO system_health_events (
  user_id,
  organization_id,
  component_type,
  component_name,
  environment,
  status,
  availability_percentage,
  latency_ms,
  latency_p50_ms,
  latency_p95_ms,
  latency_p99_ms,
  throughput_per_minute,
  error_count,
  error_rate,
  cpu_usage_percent,
  memory_usage_percent,
  measurement_window_start,
  measurement_window_end,
  measurement_window_seconds,
  tags
) VALUES
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'edge_function',
    'fusion-analyze',
    'production',
    'healthy',
    99.5,
    150,
    120,
    180,
    250,
    45,
    2,
    0.5,
    35.2,
    42.8,
    NOW() - INTERVAL '5 minutes',
    NOW(),
    300,
    ARRAY['edge_function', 'automated_collection']
  ),
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'database_query',
    'supabase_postgres',
    'production',
    'healthy',
    99.8,
    45,
    35,
    60,
    85,
    120,
    1,
    0.2,
    28.5,
    38.2,
    NOW() - INTERVAL '5 minutes',
    NOW(),
    300,
    ARRAY['database', 'automated_collection']
  ),
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'integration',
    'slack',
    'production',
    'healthy',
    98.5,
    320,
    280,
    450,
    600,
    15,
    3,
    1.5,
    NULL,
    NULL,
    NOW() - INTERVAL '5 minutes',
    NOW(),
    300,
    ARRAY['integration', 'automated_collection']
  )
ON CONFLICT DO NOTHING;

-- Insert sample anomaly signals for test users
INSERT INTO anomaly_signals (
  user_id,
  organization_id,
  anomaly_type,
  anomaly_category,
  severity,
  confidence_score,
  source_type,
  source_component_type,
  source_component_name,
  anomaly_description,
  anomaly_summary,
  baseline_value,
  observed_value,
  deviation_percentage,
  threshold_exceeded,
  pattern_type,
  detection_method,
  detection_algorithm,
  affected_components,
  business_impact,
  recommended_actions,
  detection_timestamp,
  status,
  tags
) VALUES
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'latency_spike',
    'performance',
    'medium',
    85.5,
    'system_health_event',
    'edge_function',
    'cognitive-decision-engine',
    'Latency spike detected: 450ms (baseline: 200ms, +125.0%)',
    'Edge function response time has increased significantly, likely due to increased load or resource constraints.',
    200,
    450,
    125.0,
    'latency_threshold',
    'sudden_spike',
    'statistical_analysis',
    'threshold_comparison',
    ARRAY['cognitive-decision-engine'],
    'medium',
    '["investigate_recent_deployments", "check_resource_utilization", "scale_up_resources"]',
    NOW() - INTERVAL '10 minutes',
    'detected',
    ARRAY['latency', 'performance', 'automated_detection']
  ),
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'error_rate_increase',
    'reliability',
    'high',
    92.3,
    'system_health_event',
    'integration',
    'sendgrid',
    'Error rate increase detected: 8.50% (baseline: 1.00%, +750.0%)',
    'SendGrid integration experiencing elevated error rates, possibly due to API rate limiting or authentication issues.',
    1.0,
    8.5,
    750.0,
    'error_rate_threshold',
    'gradual_increase',
    'statistical_analysis',
    'threshold_comparison',
    ARRAY['sendgrid'],
    'high',
    '["review_error_logs", "check_integration_health", "restart_affected_services"]',
    NOW() - INTERVAL '5 minutes',
    'investigating',
    ARRAY['error_rate', 'reliability', 'automated_detection']
  )
ON CONFLICT DO NOTHING;

-- Insert sample recovery actions for test users
INSERT INTO recovery_actions (
  user_id,
  organization_id,
  action_type,
  action_category,
  action_name,
  action_description,
  trigger_type,
  trigger_reason,
  target_component_type,
  target_component_name,
  action_config,
  execution_status,
  timeout_seconds,
  executed_by,
  tags
) VALUES
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'clear_cache',
    'cache',
    'clear cache - cognitive-decision-engine',
    'Self-healing action triggered by anomaly detection',
    'automatic',
    'Anomaly detected: latency_spike (medium)',
    'edge_function',
    'cognitive-decision-engine',
    '{"cache_type": "all"}',
    'pending',
    300,
    'system',
    ARRAY['self_healing', 'automated']
  )
ON CONFLICT DO NOTHING;

-- Insert sample selftest results for test users
INSERT INTO selftest_results (
  user_id,
  organization_id,
  test_name,
  test_category,
  test_type,
  test_description,
  execution_mode,
  scheduled_by,
  target_component_type,
  target_component_name,
  target_environment,
  execution_status,
  started_at,
  completed_at,
  execution_duration_ms,
  test_result,
  success,
  pass_count,
  fail_count,
  total_assertions,
  test_summary,
  health_score,
  reliability_score,
  performance_score,
  tags
) VALUES
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'Edge Function Health Check',
    'connectivity',
    'health_check',
    'Verifies all Edge Functions are responding correctly',
    'scheduled',
    'system',
    'edge_function',
    'all_functions',
    'production',
    'completed',
    NOW() - INTERVAL '1 hour',
    NOW() - INTERVAL '59 minutes',
    45000,
    'pass',
    true,
    11,
    0,
    11,
    'All Edge Functions responding normally with acceptable latency',
    98.5,
    99.2,
    97.8,
    ARRAY['health_check', 'scheduled', 'edge_functions']
  ),
  (
    (SELECT id FROM auth.users WHERE email LIKE '%test%' LIMIT 1),
    NULL,
    'Database Connection Pool Test',
    'performance',
    'load',
    'Tests database connection pool under load',
    'scheduled',
    'system',
    'database',
    'supabase_postgres',
    'production',
    'completed',
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '28 minutes',
    120000,
    'pass',
    true,
    8,
    0,
    8,
    'Database connection pool handling load efficiently',
    95.2,
    96.5,
    94.0,
    ARRAY['performance', 'scheduled', 'database']
  )
ON CONFLICT DO NOTHING;

COMMENT ON TABLE decision_events IS 'Seed data added for E2E testing - Phase 7 modules';
COMMENT ON TABLE system_health_events IS 'Seed data added for E2E testing - Phase 7 modules';
COMMENT ON TABLE anomaly_signals IS 'Seed data added for E2E testing - Phase 7 modules';
COMMENT ON TABLE recovery_actions IS 'Seed data added for E2E testing - Phase 7 modules';
COMMENT ON TABLE selftest_results IS 'Seed data added for E2E testing - Phase 7 modules';
