import PptxGenJS from 'pptxgenjs';

// ---------------------------------------------------------------------------
// Types — mirrors generateBriefPdf.ts interfaces
// ---------------------------------------------------------------------------

interface PptxSignalEntity {
  name: string;
  entity_id?: string;
  entity_type?: string;
  value?: number;
  owner?: string;
  status?: string;
  last_activity_type?: string;
  last_activity_date?: string;
  days_in_current_state?: number;
  metric_value?: number;
}

interface PptxAccountabilityItem {
  entity: string;
  owner: string;
  issue: string;
}

interface PptxPrescriptiveAction {
  who: string;
  what: string;
  when: string;
}

interface PptxBusinessImpactStructured {
  revenue_at_risk?: string;
  overdue_cash?: string;
  operational_delays?: string;
  narrative?: string;
}

interface PptxForecastData {
  '7_day'?: string;
  '14_day'?: string;
  '30_day'?: string;
}

interface PptxSignalEvidence {
  signal_type: string;
  signal_subtype?: string;
  source: string;
  severity: string;
  category: string;
  description: string;
  confidence: number;
  affected_entities: PptxSignalEntity[];
  summary_metrics: Record<string, unknown>;
}

interface PptxScoreBreakdown {
  base_score: number;
  category_penalties_capped: Record<string, number>;
  total_capped_penalty: number;
  cross_system_penalty: number;
  recovery_buffer: number;
  impacted_categories: string[];
  final_score: number;
}

export interface BriefPptxData {
  title: string;
  created_at: string;
  health_score: number | null;
  confidence: number;
  detected_signals: string[];
  business_impact: string;
  recommended_actions: string[];
  risk_assessment: string;
  momentum?: {
    classification: string;
    delta: number;
    label: string;
  } | null;
  userName?: string;
  companyLogoUrl?: string;
  signal_evidence?: PptxSignalEvidence[];
  root_cause_analysis?: string[];
  cross_system_correlation?: string;
  business_impact_structured?: PptxBusinessImpactStructured;
  forecast?: PptxForecastData;
  accountability?: PptxAccountabilityItem[];
  score_breakdown?: PptxScoreBreakdown | null;
}

// ---------------------------------------------------------------------------
// Brand constants
// ---------------------------------------------------------------------------

const COLORS = {
  primary: '0EA5E9',    // sky-500
  dark: '0F172A',       // slate-900
  darkAlt: '1E293B',    // slate-800
  text: '334155',       // slate-700
  textLight: '64748B',  // slate-500
  white: 'FFFFFF',
  green: '22C55E',
  amber: 'F59E0B',
  orange: 'F97316',
  red: 'EF4444',
  bgLight: 'F8FAFC',   // slate-50
  bgCard: 'F1F5F9',    // slate-100
};

function getHealthColor(score: number | null): string {
  if (score === null) return COLORS.textLight;
  if (score >= 90) return COLORS.green;
  if (score >= 70) return COLORS.green;
  if (score >= 50) return COLORS.amber;
  if (score >= 30) return COLORS.orange;
  return COLORS.red;
}

function getHealthLabel(score: number | null): string {
  if (score === null) return 'Unknown';
  if (score >= 90) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Moderate';
  if (score >= 30) return 'At Risk';
  if (score >= 10) return 'Critical';
  return 'System Failure';
}

function getMomentumLabel(classification: string): string {
  const labels: Record<string, string> = {
    'strong_improvement': 'Strong Improvement',
    'improving': 'Improving',
    'stable': 'Stable',
    'declining': 'Declining',
    'critical_decline': 'Critical Decline',
  };
  return labels[classification] || classification;
}

function getSeverityColor(severity: string): string {
  if (severity === 'critical' || severity === 'high') return COLORS.red;
  if (severity === 'medium') return COLORS.amber;
  return COLORS.green;
}

// ---------------------------------------------------------------------------
// Slide-level helpers
// ---------------------------------------------------------------------------

/** Add footer to every content slide */
function addSlideFooter(slide: PptxGenJS.Slide, dateStr: string) {
  slide.addText(
    [
      { text: 'Generated by Core314  |  Operational Intelligence Platform', options: { color: COLORS.textLight, fontSize: 7 } },
    ],
    { x: 0.5, y: 7.0, w: 7, h: 0.3 }
  );
  slide.addText(dateStr, { x: 7.5, y: 7.0, w: 2, h: 0.3, fontSize: 7, color: COLORS.textLight, align: 'right' });
}

/** Add a section title bar at y position */
function addSectionTitle(slide: PptxGenJS.Slide, title: string, y: number) {
  // Accent bar
  slide.addShape('rect' as PptxGenJS.ShapeType, { x: 0.5, y, w: 0.06, h: 0.28, fill: { color: COLORS.primary } });
  slide.addText(title, { x: 0.7, y, w: 8, h: 0.3, fontSize: 12, bold: true, color: COLORS.dark });
}

// ---------------------------------------------------------------------------
// Main export function
// ---------------------------------------------------------------------------

export async function generateBriefPptx(data: BriefPptxData): Promise<void> {
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5 inches
  pptx.author = 'Core314';
  pptx.subject = 'Operational Intelligence Brief';
  pptx.title = data.title;

  const dateStr = new Date(data.created_at).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const timeStr = new Date(data.created_at).toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });

  // ==========================================================================
  // SLIDE 1: Title Slide
  // ==========================================================================
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: COLORS.dark };

  // Company logo (top-left) if provided
  if (data.companyLogoUrl) {
    try {
      titleSlide.addImage({ path: data.companyLogoUrl, x: 0.6, y: 0.5, h: 0.8, w: 2.4, sizing: { type: 'contain', w: 2.4, h: 0.8 } });
    } catch {
      // Skip logo if fetch fails — don't break the export
    }
  }

  // Core314 branding (top-right)
  titleSlide.addText('Core314', { x: 9.5, y: 0.6, w: 3, h: 0.4, fontSize: 14, color: COLORS.primary, align: 'right', fontFace: 'Arial' });
  titleSlide.addText('Operational Intelligence Platform', { x: 9.5, y: 0.95, w: 3, h: 0.3, fontSize: 9, color: COLORS.textLight, align: 'right' });

  // Title
  titleSlide.addText('Operational Intelligence Brief', { x: 0.6, y: 2.2, w: 12, h: 0.7, fontSize: 28, bold: true, color: COLORS.white, fontFace: 'Arial' });

  // Brief title
  titleSlide.addText(data.title, { x: 0.6, y: 3.0, w: 10, h: 0.6, fontSize: 16, color: COLORS.primary, fontFace: 'Arial' });

  // Date + time
  titleSlide.addText(`${dateStr}  •  ${timeStr}`, { x: 0.6, y: 3.8, w: 6, h: 0.3, fontSize: 11, color: COLORS.textLight });

  // Prepared for
  if (data.userName) {
    titleSlide.addText(`Prepared for: ${data.userName}`, { x: 0.6, y: 4.2, w: 6, h: 0.3, fontSize: 11, color: '94A3B8' });
  }

  // Health score badge (bottom-right)
  if (data.health_score !== null) {
    const healthColor = getHealthColor(data.health_score);
    const healthLabel = getHealthLabel(data.health_score);
    titleSlide.addShape('roundRect' as PptxGenJS.ShapeType, { x: 9.0, y: 5.5, w: 3.5, h: 1.2, rectRadius: 0.15, fill: { color: COLORS.darkAlt } });
    titleSlide.addText(`${data.health_score}`, { x: 9.2, y: 5.55, w: 1.5, h: 0.8, fontSize: 36, bold: true, color: healthColor, align: 'center', valign: 'middle' });
    titleSlide.addText('/ 100', { x: 10.4, y: 5.7, w: 0.8, h: 0.3, fontSize: 11, color: COLORS.textLight });
    titleSlide.addText(healthLabel, { x: 9.2, y: 6.3, w: 1.5, h: 0.3, fontSize: 11, bold: true, color: healthColor, align: 'center' });

    // Momentum
    if (data.momentum) {
      const momLabel = getMomentumLabel(data.momentum.classification);
      const deltaStr = `${data.momentum.delta >= 0 ? '+' : ''}${data.momentum.delta}`;
      const momColor = data.momentum.delta >= 0 ? COLORS.green : data.momentum.delta < -5 ? COLORS.red : COLORS.amber;
      titleSlide.addText(`${momLabel} (${deltaStr})`, { x: 10.8, y: 5.85, w: 1.6, h: 0.3, fontSize: 10, bold: true, color: momColor, align: 'center' });
    }
  }

  // Confidential + confidence
  const confidenceLabel = data.confidence >= 80 ? 'High Confidence' : data.confidence >= 60 ? 'Moderate Confidence' : 'Low Confidence';
  titleSlide.addText(`CONFIDENTIAL  •  ${confidenceLabel} (${data.confidence}%)`, { x: 0.6, y: 6.8, w: 6, h: 0.25, fontSize: 8, color: COLORS.textLight });

  // ==========================================================================
  // SLIDE 2: Executive Summary (Health + Correlation + Business Impact)
  // ==========================================================================
  const summarySlide = pptx.addSlide();
  summarySlide.background = { color: COLORS.white };
  addSlideFooter(summarySlide, dateStr);

  // Company logo on content slides
  if (data.companyLogoUrl) {
    try {
      summarySlide.addImage({ path: data.companyLogoUrl, x: 10.5, y: 0.2, h: 0.5, w: 1.5, sizing: { type: 'contain', w: 1.5, h: 0.5 } });
    } catch { /* skip */ }
  }

  summarySlide.addText('Executive Summary', { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

  // Health Score card
  let sumY = 1.0;
  if (data.health_score !== null) {
    const healthColor = getHealthColor(data.health_score);
    summarySlide.addShape('roundRect' as PptxGenJS.ShapeType, { x: 0.5, y: sumY, w: 3.8, h: 1.4, rectRadius: 0.1, fill: { color: COLORS.bgCard } });
    summarySlide.addText('HEALTH SCORE', { x: 0.7, y: sumY + 0.1, w: 3, h: 0.25, fontSize: 8, bold: true, color: COLORS.textLight });
    summarySlide.addText(`${data.health_score} / 100`, { x: 0.7, y: sumY + 0.35, w: 2, h: 0.5, fontSize: 28, bold: true, color: healthColor });
    summarySlide.addText(getHealthLabel(data.health_score), { x: 0.7, y: sumY + 0.85, w: 3, h: 0.3, fontSize: 12, bold: true, color: healthColor });

    if (data.momentum) {
      const momColor = data.momentum.delta >= 0 ? COLORS.green : data.momentum.delta < -5 ? COLORS.red : COLORS.amber;
      const arrow = data.momentum.delta >= 0 ? '↑' : '↓';
      summarySlide.addText(`${arrow} ${getMomentumLabel(data.momentum.classification)} (${data.momentum.delta >= 0 ? '+' : ''}${data.momentum.delta})`, {
        x: 2.5, y: sumY + 0.35, w: 1.7, h: 0.3, fontSize: 9, bold: true, color: momColor,
      });
    }
  }

  // Business Impact cards (side by side)
  if (data.business_impact_structured) {
    const bis = data.business_impact_structured;
    const impactItems: { label: string; value: string; color: string }[] = [];
    if (bis.revenue_at_risk) impactItems.push({ label: 'Revenue at Risk', value: bis.revenue_at_risk, color: COLORS.red });
    if (bis.overdue_cash) impactItems.push({ label: 'Overdue Cash', value: bis.overdue_cash, color: COLORS.amber });
    if (bis.operational_delays) impactItems.push({ label: 'Operational Delays', value: bis.operational_delays, color: COLORS.orange });

    const cardW = 3.8;
    const startX = 4.8;
    impactItems.forEach((item, idx) => {
      const cx = startX + idx * (cardW + 0.3);
      if (cx + cardW <= 13) {
        summarySlide.addShape('roundRect' as PptxGenJS.ShapeType, { x: cx, y: sumY, w: cardW > 2.5 ? 2.5 : cardW, h: 1.4, rectRadius: 0.1, fill: { color: COLORS.bgCard } });
        summarySlide.addText(item.label.toUpperCase(), { x: cx + 0.2, y: sumY + 0.1, w: 2.2, h: 0.25, fontSize: 8, bold: true, color: COLORS.textLight });
        summarySlide.addText(item.value, { x: cx + 0.2, y: sumY + 0.4, w: 2.2, h: 0.4, fontSize: 18, bold: true, color: item.color });
      }
    });
  }

  sumY += 1.7;

  // Cross-system correlation
  if (data.cross_system_correlation) {
    addSectionTitle(summarySlide, 'CROSS-SYSTEM CORRELATION', sumY);
    sumY += 0.45;
    summarySlide.addText(data.cross_system_correlation, { x: 0.7, y: sumY, w: 11.5, h: 0.6, fontSize: 11, color: COLORS.text, valign: 'top' });
    sumY += 0.7;
  }

  // Business impact narrative
  if (data.business_impact_structured?.narrative) {
    addSectionTitle(summarySlide, 'BUSINESS IMPACT NARRATIVE', sumY);
    sumY += 0.45;
    summarySlide.addText(data.business_impact_structured.narrative, { x: 0.7, y: sumY, w: 11.5, h: 1.0, fontSize: 10, color: COLORS.text, valign: 'top' });
    sumY += 1.1;
  } else if (data.business_impact) {
    addSectionTitle(summarySlide, 'BUSINESS IMPACT', sumY);
    sumY += 0.45;
    summarySlide.addText(data.business_impact, { x: 0.7, y: sumY, w: 11.5, h: 1.0, fontSize: 10, color: COLORS.text, valign: 'top' });
    sumY += 1.1;
  }

  // Risk assessment
  if (data.risk_assessment) {
    addSectionTitle(summarySlide, 'RISK ASSESSMENT', sumY);
    sumY += 0.45;
    summarySlide.addText(data.risk_assessment, { x: 0.7, y: sumY, w: 11.5, h: 0.8, fontSize: 10, color: COLORS.text, valign: 'top' });
  }

  // ==========================================================================
  // SLIDE 3: Detected Signals
  // ==========================================================================
  if (data.signal_evidence && data.signal_evidence.length > 0) {
    // Possibly split across multiple slides if many signals
    const signalsPerSlide = 3;
    for (let chunk = 0; chunk < data.signal_evidence.length; chunk += signalsPerSlide) {
      const signalSlide = pptx.addSlide();
      signalSlide.background = { color: COLORS.white };
      addSlideFooter(signalSlide, dateStr);

      if (data.companyLogoUrl) {
        try {
          signalSlide.addImage({ path: data.companyLogoUrl, x: 10.5, y: 0.2, h: 0.5, w: 1.5, sizing: { type: 'contain', w: 1.5, h: 0.5 } });
        } catch { /* skip */ }
      }

      const pageLabel = data.signal_evidence.length > signalsPerSlide
        ? ` (${Math.floor(chunk / signalsPerSlide) + 1}/${Math.ceil(data.signal_evidence.length / signalsPerSlide)})`
        : '';
      signalSlide.addText(`Detected Signals${pageLabel}`, { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

      let sigY = 1.0;
      const sliceEnd = Math.min(chunk + signalsPerSlide, data.signal_evidence.length);
      for (let si = chunk; si < sliceEnd; si++) {
        const ev = data.signal_evidence[si];
        const sevColor = getSeverityColor(ev.severity);

        // Signal card background
        signalSlide.addShape('roundRect' as PptxGenJS.ShapeType, {
          x: 0.5, y: sigY, w: 12, h: 1.8, rectRadius: 0.1,
          fill: { color: COLORS.bgLight },
          line: { color: sevColor, width: 1, dashType: 'solid' },
        });

        // Severity badge
        signalSlide.addShape('roundRect' as PptxGenJS.ShapeType, { x: 0.7, y: sigY + 0.15, w: 0.7, h: 0.25, rectRadius: 0.05, fill: { color: sevColor } });
        signalSlide.addText(ev.severity.toUpperCase(), { x: 0.7, y: sigY + 0.15, w: 0.7, h: 0.25, fontSize: 7, bold: true, color: COLORS.white, align: 'center', valign: 'middle' });

        // Source + subtype
        const sourceLabel = ev.signal_subtype
          ? `${ev.source.replace(/_/g, ' ').toUpperCase()} — ${ev.signal_subtype}`
          : `${ev.source.replace(/_/g, ' ').toUpperCase()} · ${ev.category.replace(/_/g, ' ')}`;
        signalSlide.addText(sourceLabel, { x: 1.55, y: sigY + 0.12, w: 6, h: 0.3, fontSize: 9, color: COLORS.textLight });

        // Description
        signalSlide.addText(ev.description, { x: 0.7, y: sigY + 0.45, w: 11.5, h: 0.35, fontSize: 10, color: COLORS.text, valign: 'top' });

        // Entity details (compact table-like layout)
        if (ev.affected_entities.length > 0) {
          const entitiesToShow = ev.affected_entities.slice(0, 5);
          let entY = sigY + 0.85;
          signalSlide.addText(`Entity Details (${ev.affected_entities.length}):`, { x: 0.7, y: entY, w: 4, h: 0.2, fontSize: 8, bold: true, color: COLORS.textLight });
          entY += 0.22;

          for (const ent of entitiesToShow) {
            const metaParts: string[] = [];
            if (ent.entity_id) metaParts.push(`ID: ${ent.entity_id}`);
            if (ent.value !== undefined) metaParts.push(`$${ent.value.toLocaleString()}`);
            if (ent.owner) metaParts.push(`Owner: ${ent.owner}`);
            if (ent.status) metaParts.push(`Status: ${ent.status}`);
            if (ent.days_in_current_state !== undefined) metaParts.push(`${ent.days_in_current_state}d in state`);

            signalSlide.addText(`• ${ent.name}`, { x: 0.9, y: entY, w: 4, h: 0.18, fontSize: 8, bold: true, color: COLORS.text });
            if (metaParts.length > 0) {
              signalSlide.addText(metaParts.join('  |  '), { x: 5.0, y: entY, w: 7.5, h: 0.18, fontSize: 7, color: COLORS.textLight });
            }
            entY += 0.18;
          }
          if (ev.affected_entities.length > 5) {
            signalSlide.addText(`+${ev.affected_entities.length - 5} more...`, { x: 0.9, y: entY, w: 4, h: 0.16, fontSize: 7, italic: true, color: COLORS.textLight });
          }
        }

        sigY += 2.0;
      }
    }
  } else if (data.detected_signals.length > 0) {
    // Fallback: plain text signals
    const sigSlide = pptx.addSlide();
    sigSlide.background = { color: COLORS.white };
    addSlideFooter(sigSlide, dateStr);
    sigSlide.addText('Detected Signals', { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

    let sigY = 1.0;
    for (const signal of data.detected_signals) {
      sigSlide.addText(`• ${signal}`, { x: 0.7, y: sigY, w: 11.5, h: 0.35, fontSize: 11, color: COLORS.text, valign: 'top' });
      sigY += 0.4;
      if (sigY > 6.5) break;
    }
  }

  // ==========================================================================
  // SLIDE 4: Root Cause Analysis + Forecast
  // ==========================================================================
  const hasRootCause = data.root_cause_analysis && data.root_cause_analysis.length > 0;
  const hasForecast = data.forecast && (data.forecast['7_day'] || data.forecast['14_day'] || data.forecast['30_day']);

  if (hasRootCause || hasForecast) {
    const analysisSlide = pptx.addSlide();
    analysisSlide.background = { color: COLORS.white };
    addSlideFooter(analysisSlide, dateStr);

    if (data.companyLogoUrl) {
      try {
        analysisSlide.addImage({ path: data.companyLogoUrl, x: 10.5, y: 0.2, h: 0.5, w: 1.5, sizing: { type: 'contain', w: 1.5, h: 0.5 } });
      } catch { /* skip */ }
    }

    analysisSlide.addText('Analysis & Forecast', { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

    let anaY = 1.0;

    // Root Cause Analysis
    if (hasRootCause && data.root_cause_analysis) {
      addSectionTitle(analysisSlide, 'ROOT CAUSE ANALYSIS', anaY);
      anaY += 0.45;

      for (const cause of data.root_cause_analysis) {
        analysisSlide.addText(`⚠  ${cause}`, { x: 0.7, y: anaY, w: 11.5, h: 0.35, fontSize: 10, color: COLORS.text, valign: 'top' });
        anaY += 0.38;
      }
      anaY += 0.3;
    }

    // Forecast Projections
    if (hasForecast && data.forecast) {
      addSectionTitle(analysisSlide, 'FORECAST PROJECTIONS', anaY);
      anaY += 0.5;

      const forecasts: { label: string; text: string; color: string }[] = [];
      if (data.forecast['7_day']) forecasts.push({ label: '7-Day Outlook', text: data.forecast['7_day'], color: COLORS.primary });
      if (data.forecast['14_day']) forecasts.push({ label: '14-Day Outlook', text: data.forecast['14_day'], color: COLORS.amber });
      if (data.forecast['30_day']) forecasts.push({ label: '30-Day Outlook', text: data.forecast['30_day'], color: COLORS.red });

      const fcCardW = 3.8;
      forecasts.forEach((fc, idx) => {
        const cx = 0.5 + idx * (fcCardW + 0.3);
        analysisSlide.addShape('roundRect' as PptxGenJS.ShapeType, { x: cx, y: anaY, w: fcCardW, h: 1.8, rectRadius: 0.1, fill: { color: COLORS.bgCard } });
        // Colored top accent
        analysisSlide.addShape('rect' as PptxGenJS.ShapeType, { x: cx, y: anaY, w: fcCardW, h: 0.06, fill: { color: fc.color } });
        analysisSlide.addText(fc.label, { x: cx + 0.2, y: anaY + 0.15, w: fcCardW - 0.4, h: 0.25, fontSize: 10, bold: true, color: fc.color });
        analysisSlide.addText(fc.text, { x: cx + 0.2, y: anaY + 0.45, w: fcCardW - 0.4, h: 1.2, fontSize: 9, color: COLORS.text, valign: 'top' });
      });
    }
  }

  // ==========================================================================
  // SLIDE 5: Accountability Table
  // ==========================================================================
  if (data.accountability && data.accountability.length > 0) {
    const acctSlide = pptx.addSlide();
    acctSlide.background = { color: COLORS.white };
    addSlideFooter(acctSlide, dateStr);

    if (data.companyLogoUrl) {
      try {
        acctSlide.addImage({ path: data.companyLogoUrl, x: 10.5, y: 0.2, h: 0.5, w: 1.5, sizing: { type: 'contain', w: 1.5, h: 0.5 } });
      } catch { /* skip */ }
    }

    acctSlide.addText('Accountability', { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

    // Build table rows
    const headerRow: PptxGenJS.TableRow = [
      { text: 'ENTITY', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
      { text: 'OWNER', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
      { text: 'ISSUE', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
    ];

    const dataRows: PptxGenJS.TableRow[] = data.accountability.map((item, idx) => {
      const bgColor = idx % 2 === 0 ? COLORS.white : COLORS.bgLight;
      return [
        { text: item.entity, options: { fontSize: 9, color: COLORS.text, fill: { color: bgColor }, valign: 'middle' } },
        { text: item.owner, options: { fontSize: 9, bold: true, color: COLORS.primary, fill: { color: bgColor }, valign: 'middle' } },
        { text: item.issue, options: { fontSize: 9, color: COLORS.textLight, fill: { color: bgColor }, valign: 'middle' } },
      ];
    });

    acctSlide.addTable([headerRow, ...dataRows], {
      x: 0.5, y: 1.0, w: 12,
      colW: [4, 3, 5],
      rowH: 0.4,
      border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
    });
  }

  // ==========================================================================
  // SLIDE 6: Recommended Actions Table
  // ==========================================================================
  if (data.recommended_actions && data.recommended_actions.length > 0) {
    const actionsSlide = pptx.addSlide();
    actionsSlide.background = { color: COLORS.white };
    addSlideFooter(actionsSlide, dateStr);

    if (data.companyLogoUrl) {
      try {
        actionsSlide.addImage({ path: data.companyLogoUrl, x: 10.5, y: 0.2, h: 0.5, w: 1.5, sizing: { type: 'contain', w: 1.5, h: 0.5 } });
      } catch { /* skip */ }
    }

    actionsSlide.addText('Recommended Actions', { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

    // Check if structured WHO-WHAT-WHEN format
    const firstAction = data.recommended_actions[0];
    const isStructured = typeof firstAction === 'object' && 'who' in (firstAction as Record<string, unknown>);

    if (isStructured) {
      const headerRow: PptxGenJS.TableRow = [
        { text: 'WHO', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
        { text: 'WHAT', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
        { text: 'WHEN', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
      ];

      const dataRows: PptxGenJS.TableRow[] = data.recommended_actions.map((rawAction, idx) => {
        const action = rawAction as unknown as PptxPrescriptiveAction;
        const bgColor = idx % 2 === 0 ? COLORS.white : COLORS.bgLight;
        return [
          { text: action.who || '', options: { fontSize: 9, bold: true, color: COLORS.primary, fill: { color: bgColor }, valign: 'middle' } },
          { text: action.what || '', options: { fontSize: 9, color: COLORS.text, fill: { color: bgColor }, valign: 'middle' } },
          { text: action.when || '', options: { fontSize: 9, bold: true, color: COLORS.amber, fill: { color: bgColor }, valign: 'middle' } },
        ];
      });

      actionsSlide.addTable([headerRow, ...dataRows], {
        x: 0.5, y: 1.0, w: 12,
        colW: [3, 6, 3],
        rowH: 0.45,
        border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
      });
    } else {
      // Plain text actions
      let actY = 1.0;
      for (let i = 0; i < data.recommended_actions.length; i++) {
        const action = typeof data.recommended_actions[i] === 'string' ? data.recommended_actions[i] : String(data.recommended_actions[i]);
        actionsSlide.addText(`${i + 1}.  ${action}`, { x: 0.7, y: actY, w: 11.5, h: 0.4, fontSize: 11, color: COLORS.text, valign: 'top' });
        actY += 0.45;
      }
    }
  }

  // ==========================================================================
  // SLIDE 7: Health Score Breakdown (if available)
  // ==========================================================================
  if (data.score_breakdown) {
    const bdSlide = pptx.addSlide();
    bdSlide.background = { color: COLORS.white };
    addSlideFooter(bdSlide, dateStr);

    if (data.companyLogoUrl) {
      try {
        bdSlide.addImage({ path: data.companyLogoUrl, x: 10.5, y: 0.2, h: 0.5, w: 1.5, sizing: { type: 'contain', w: 1.5, h: 0.5 } });
      } catch { /* skip */ }
    }

    bdSlide.addText('Health Score Breakdown', { x: 0.5, y: 0.3, w: 8, h: 0.5, fontSize: 22, bold: true, color: COLORS.dark });

    const bd = data.score_breakdown;
    const CATEGORY_LABELS: Record<string, string> = {
      revenue: 'Revenue Impact',
      cash_flow: 'Cash Flow Impact',
      operations: 'Operations Impact',
      communication: 'Communication Impact',
      scheduling: 'Scheduling Impact',
    };

    // Build breakdown table
    const rows: PptxGenJS.TableRow[] = [];

    // Header
    rows.push([
      { text: 'COMPONENT', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle' } },
      { text: 'VALUE', options: { fontSize: 9, bold: true, color: COLORS.white, fill: { color: COLORS.dark }, valign: 'middle', align: 'right' } },
    ]);

    // Base score
    rows.push([
      { text: 'Base Score', options: { fontSize: 10, color: COLORS.text, fill: { color: COLORS.white }, valign: 'middle' } },
      { text: String(bd.base_score), options: { fontSize: 10, color: COLORS.text, fill: { color: COLORS.white }, valign: 'middle', align: 'right' } },
    ]);

    // Category penalties
    for (const [cat, penalty] of Object.entries(bd.category_penalties_capped || {})) {
      const label = CATEGORY_LABELS[cat] || cat.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      rows.push([
        { text: label, options: { fontSize: 10, color: COLORS.text, fill: { color: COLORS.bgLight }, valign: 'middle' } },
        { text: penalty > 0 ? `-${penalty}` : '0', options: { fontSize: 10, bold: penalty > 0, color: penalty > 0 ? COLORS.red : COLORS.textLight, fill: { color: COLORS.bgLight }, valign: 'middle', align: 'right' } },
      ]);
    }

    // Cross-system penalty
    if (bd.cross_system_penalty > 0) {
      rows.push([
        { text: 'Correlation Penalty', options: { fontSize: 10, color: COLORS.text, fill: { color: COLORS.white }, valign: 'middle' } },
        { text: `-${bd.cross_system_penalty}`, options: { fontSize: 10, bold: true, color: COLORS.red, fill: { color: COLORS.white }, valign: 'middle', align: 'right' } },
      ]);
    }

    // Recovery buffer
    if (bd.recovery_buffer > 0) {
      rows.push([
        { text: 'Recovery Offset', options: { fontSize: 10, color: COLORS.text, fill: { color: COLORS.bgLight }, valign: 'middle' } },
        { text: `+${bd.recovery_buffer}`, options: { fontSize: 10, bold: true, color: COLORS.green, fill: { color: COLORS.bgLight }, valign: 'middle', align: 'right' } },
      ]);
    }

    // Final score
    const finalColor = getHealthColor(bd.final_score);
    rows.push([
      { text: 'FINAL SCORE', options: { fontSize: 11, bold: true, color: COLORS.dark, fill: { color: COLORS.bgCard }, valign: 'middle' } },
      { text: String(bd.final_score), options: { fontSize: 14, bold: true, color: finalColor, fill: { color: COLORS.bgCard }, valign: 'middle', align: 'right' } },
    ]);

    bdSlide.addTable(rows, {
      x: 2, y: 1.2, w: 8,
      colW: [5, 3],
      rowH: 0.45,
      border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
    });
  }

  // ==========================================================================
  // Generate and download
  // ==========================================================================
  const safeTitle = data.title.replace(/[^a-zA-Z0-9 ]/g, '').substring(0, 40).trim().replace(/\s+/g, '_');
  const fileName = `Core314_Brief_${safeTitle}_${new Date(data.created_at).toISOString().slice(0, 10)}`;
  await pptx.writeFile({ fileName });
}
