import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import Footer from '../components/Footer';

export default function AIDisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-sky-600 hover:text-sky-700 mb-8 transition-colors"
        >
          <ArrowLeft className="h-5 w-5" />
          Back to Home
        </Link>

        <div className="bg-white border border-slate-200 rounded-2xl p-8 md:p-12 shadow-sm">
          <h1 className="text-4xl font-bold mb-8 text-slate-900" style={{ fontFamily: 'Poppins, sans-serif' }}>
            AI & Decision Support Disclaimer
          </h1>

          <div className="prose prose-slate max-w-none space-y-8 text-slate-600" style={{ fontFamily: 'Inter, sans-serif' }}>
            <p className="text-sm text-slate-500">Last Updated: January 7, 2026</p>

            <div className="bg-amber-50 border border-amber-200 rounded-lg p-6">
              <p className="text-amber-800 font-semibold text-lg mb-2">
                Important Notice Regarding AI-Generated Outputs
              </p>
              <p className="text-amber-700">
                                This disclaimer applies to all artificial intelligence features, insights, analyses, and outputs 
                                provided by the Core314™ platform. Please read this disclaimer carefully before using our services.
              </p>
            </div>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Nature of Service</h2>
              <p>
                Core314 provides decision intelligence, analytical insights, and operational observations through 
                its system intelligence platform. The platform uses artificial intelligence and machine learning 
                technologies to analyze data from your connected systems and generate insights.
              </p>
              <p className="mt-4 font-semibold text-slate-800">
                Core314 does NOT make decisions on behalf of users. All outputs are advisory and informational only.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>User Responsibility</h2>
              <p className="font-semibold text-slate-800">
                You remain solely responsible for all decisions and actions taken based on information provided 
                by the Core314 platform.
              </p>
              <p className="mt-4">
                The insights, analyses, scores, predictions, and other outputs generated by Core314 are intended 
                to support and inform your decision-making processes. They are not intended to replace human 
                judgment, professional expertise, or independent verification.
              </p>
              <p className="mt-4">
                Before acting on any information provided by Core314, you should:
              </p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Independently verify the accuracy and relevance of the information</li>
                <li>Consider the information in the context of your specific situation and requirements</li>
                <li>Consult with qualified professionals when appropriate</li>
                <li>Exercise your own judgment and expertise</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Limitations of AI Outputs</h2>
              <p>
                AI-generated insights and analyses may be incomplete, inaccurate, or incorrect. The outputs 
                provided by Core314 are based on the data available to the system and the algorithms used to 
                process that data. These outputs have inherent limitations:
              </p>
              <ul className="list-disc pl-6 mt-4 space-y-2">
                <li><strong>Data Dependency:</strong> Outputs are only as good as the data provided. Incomplete, 
                inaccurate, or outdated data will affect the quality of insights.</li>
                <li><strong>Pattern Recognition:</strong> AI systems identify patterns based on historical data, 
                which may not accurately predict future outcomes or account for unprecedented situations.</li>
                <li><strong>Context Limitations:</strong> AI cannot fully understand the nuanced context of your 
                specific business situation, industry dynamics, or organizational factors.</li>
                <li><strong>Technical Limitations:</strong> All AI systems have technical limitations and may 
                produce errors, inconsistencies, or unexpected results.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>No Guarantee of Accuracy</h2>
              <p className="font-semibold uppercase text-slate-800">
                CORE314 MAKES NO GUARANTEE OF THE ACCURACY, RELIABILITY, COMPLETENESS, OR FITNESS FOR PURPOSE 
                OF ANY AI-GENERATED OUTPUT.
              </p>
              <p className="mt-4">
                While we strive to provide useful and accurate insights, we cannot and do not warrant that:
              </p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Any insight, analysis, or prediction will be accurate or correct</li>
                <li>Any score or metric will accurately reflect actual conditions</li>
                <li>Any recommendation or suggestion will be appropriate for your situation</li>
                <li>Any forecast or projection will accurately predict future outcomes</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Human Judgment Required</h2>
              <p className="font-semibold text-slate-800">
                Human judgment is required at all times when using Core314.
              </p>
              <p className="mt-4">
                The Core314 platform is designed to augment human decision-making, not replace it. AI-generated 
                outputs should be treated as one input among many in your decision-making process. Critical 
                decisions should always involve appropriate human review, expertise, and judgment.
              </p>
              <p className="mt-4">
                Do not rely solely on Core314 outputs for decisions that could have significant financial, 
                operational, legal, or other material consequences.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Disclaimer of Liability</h2>
              <p className="font-semibold uppercase text-slate-800">
                CORE314 TECHNOLOGIES LLC DISCLAIMS ALL LIABILITY ARISING FROM OR RELATED TO YOUR RELIANCE ON 
                AI-GENERATED OUTPUTS.
              </p>
              <p className="mt-4">
                To the maximum extent permitted by applicable law, Core314 shall not be liable for any damages, 
                losses, costs, or expenses arising from:
              </p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Decisions made based on AI-generated insights or analyses</li>
                <li>Actions taken or not taken in reliance on platform outputs</li>
                <li>Inaccuracies, errors, or omissions in AI-generated content</li>
                <li>Failure of AI outputs to predict or identify issues</li>
                <li>Any other use of or reliance on the platform's AI features</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Not Professional Advice</h2>
              <p>
                Core314 outputs do not constitute legal, financial, medical, operational, or any other form of 
                professional advice. The platform is not a substitute for professional consultation or expertise 
                in any field.
              </p>
              <p className="mt-4">
                If you require professional advice, you should consult with appropriately qualified professionals 
                who can consider your specific circumstances.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Acceptance</h2>
              <p>
                By using the Core314 platform and its AI features, you acknowledge that you have read, understood, 
                and agree to this AI & Decision Support Disclaimer. You accept full responsibility for how you 
                use and act upon information provided by the platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-900 mb-4" style={{ fontFamily: 'Poppins, sans-serif' }}>Contact Information</h2>
              <p>
                If you have questions about this disclaimer, please contact us at:
              </p>
              <p className="mt-4">
                      <strong>Core314™ Technologies LLC</strong><br />
                      Email:{' '}
                      <a href="mailto:support@core314.com" className="text-sky-600 hover:text-sky-700 underline">
                        support@core314.com
                      </a>
                    </p>
                    <p className="text-xs text-slate-400 mt-4">
                      Patent Pending
                    </p>
                  </section>
                </div>
              </div>
            </div>

            <Footer />
    </div>
  );
}
